line-length = 127
indent-width = 4
[lint]
select = ["ALL"]
ignore = [
    "missing-copyright-notice",
    "D",
    "DOC",
    "S",
    "T20",
    "line-too-long",
    "mutable-class-default",
    "non-pep695-type-alias",
    "outdated-version-block",
    "hardcoded-bind-all-interfaces",
    "try-except-in-loop",
    "magic-value-comparison",
    "too-many-public-methods",
    "no-self-use",
    "unused-async",
    "missing-trailing-comma",
]
preview = true
fixable = ["ALL"]
[format]
preview = true
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true

[lint.pydocstyle]
convention = "google"
