#!/usr/bin/env python3
"""Generate static PEP 503 index pages from GitHub release assets."""

from __future__ import annotations

import html
import json
import operator
import os
import shutil
import subprocess
from pathlib import Path


def gh_api_json(repo: str, path: str) -> list[dict]:
    output = subprocess.check_output(["gh", "api", f"/repos/{repo}/{path}"], text=True)
    return json.loads(output)


def fetch_releases(repo: str) -> list[dict]:
    releases: list[dict] = []
    page = 1
    while True:
        chunk = gh_api_json(repo, f"releases?per_page=100&page={page}")
        if not chunk:
            break
        releases.extend(chunk)
        page += 1
    return releases


def parse_packages(releases: list[dict]) -> dict[str, list[tuple[str, str, str]]]:
    packages: dict[str, list[tuple[str, str, str]]] = {}
    for rel in releases:
        assets = rel.get("assets", [])
        for asset in assets:
            name = asset["name"]
            if not name.endswith(".whl"):
                continue
            digest_raw = asset.get("digest", "")
            sha256 = digest_raw[len("sha256:") :] if digest_raw.startswith("sha256:") else ""
            pkg_name = name.split("-")[0].replace("_", "-").lower()
            packages.setdefault(pkg_name, []).append((name, asset["url"], sha256))
    return packages


def generate(repo: str, output_dir: Path) -> None:
    pages_dir = output_dir
    simple_dir = pages_dir / "simple"

    if pages_dir.exists():
        shutil.rmtree(pages_dir)
    simple_dir.mkdir(parents=True, exist_ok=True)

    releases = fetch_releases(repo)
    if not releases:
        print("No releases found, nothing to index.")
        return

    packages = parse_packages(releases)

    for pkg, wheels in sorted(packages.items()):
        pkg_dir = simple_dir / pkg
        pkg_dir.mkdir(exist_ok=True)
        links = []
        for whl_name, url, sha256 in sorted(wheels, key=operator.itemgetter(0)):
            href = f"{url}#sha256={sha256}" if sha256 else url
            links.append(
                f'<a href="{href}" data-requires-python="&gt;=3.13">{html.escape(whl_name)}</a>'
            )
        (pkg_dir / "index.html").write_text(
            "<!DOCTYPE html><html><head><meta charset='utf-8'>"
            f"<title>Links for {pkg}</title></head><body>"
            f"<h1>Links for {pkg}</h1>\n"
            + "<br>\n".join(links)
            + "\n</body></html>\n",
            encoding="utf-8",
        )

    pkg_links = "\n".join(f'<a href="{pkg}/">{pkg}</a>' for pkg in sorted(packages))
    (simple_dir / "index.html").write_text(
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        "<title>Simple Index</title></head><body>"
        "<h1>Simple Index</h1>\n"
        + pkg_links
        + "\n</body></html>\n",
        encoding="utf-8",
    )

    pkg_rows = "\n".join(
        f"<tr><td><a href='simple/{pkg}/'>{pkg}</a></td><td>{len(wheels)} wheel(s)</td></tr>"
        for pkg, wheels in sorted(packages.items())
    )
    owner, repo_name = repo.split("/")
    (pages_dir / "index.html").write_text(
        "<!DOCTYPE html><html><head><meta charset='utf-8'>"
        "<title>Mobile Python Wheels</title></head><body>"
        "<h1>Mobile Python Wheels</h1>"
        "<p>Android wheels for aiohttp and its C dependencies.</p>"
        "<p>Install via pip:<br>"
        f"<code>pip install aiohttp --extra-index-url https://{owner}.github.io/{repo_name}/simple/</code></p>"
        "<table border='1' cellpadding='6'>"
        "<tr><th>Package</th><th>Wheels</th></tr>\n"
        + pkg_rows
        + "\n</table>"
        "<p><a href='simple/'>Browse simple index</a></p>"
        f"<p>Generated by <a href='https://github.com/{owner}/{repo_name}'>{owner}/{repo_name}</a></p>"
        "</body></html>\n",
        encoding="utf-8",
    )

    print(f"Generated index for: {sorted(packages)}")
    total_wheels = sum(len(wheels) for wheels in packages.values())
    print(f"Total wheels indexed: {total_wheels}")


def main() -> None:
    repo = os.environ["GITHUB_REPOSITORY"]
    generate(repo=repo, output_dir=Path("gh-pages-index"))


if __name__ == "__main__":
    main()
